networks:
  default:
    name: expense
    driver: bridge
volumes:
  mysql:
services:
 mysql:
  image: mysql:v1
  container_name: mysql
  environment:
    MYSQL_ROOT_PASSWORD: "ExpenseApp@1"
    DB_NAME: transactions
  volumes:
      - mysql:/var/lib/mysql
 backend:
  image: backend:v1
  container_name: backend
  environment:
    DB_HOST: mysql
    DB_USER: expense
    DB_PWD: ExpenseApp@1
    DB_DATABASE: transactions
  depends_on:
    - mysql
 frontend:
  image: frontend:v1
  container_name: frontend
  depends_on:
    - backend
    - mysql
  ports:
    - 80:80

    
